version: "3.7"

services:
  mongo:
    image: mongo:4.2
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - /data/db
    ports:
      - 27017:27017
    restart: on-failure
    networks:
      - internal
    command: mongod

volumes:
  data-volume:

# Networks to be created to facilitate communication between containers
networks:
  internal:
    driver: bridge
